<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-ENTNF9ES" ignored="0" name="test1" tests="3" failures="1" timestamp="2023-04-07T12:48:32 IST" time="0.079" errors="0">
  <testcase name="failedTest" time="0.016" classname="maven.big.test.testngReport">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at maven.big.test.testngReport.failedTest(testngReport.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- failedTest -->
  <testcase name="passTest" time="0.015" classname="maven.big.test.testngReport"/>
  <testcase name="skipTest" time="0.0" classname="maven.big.test.testngReport">
    <skipped/>
  </testcase> <!-- skipTest -->
</testsuite> <!-- test1 -->
